service:
  name: bus-service

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  environment:
    BUS_LINES_TABLE_NAME: ${self:custom.BusLinesTable.name}
    BUS_TYPES_TABLE_NAME: ${self:custom.BusTypesTable.name}
  iamRoleStatements:
    - ${file(iam/BusLinesTableIAM.yml):BusLinesTableIAM}
    - ${file(iam/BusTypesTableIAM.yml):BusTypesTableIAM}

resources:
  Resources:
    BusLinesTable: ${file(resources/BusLinesTable.yml):BusLinesTable}
    BusTypesTable: ${file(resources/BusTypesTable.yml):BusTypesTable}
  
functions:
  createBusLine:
    handler: src/handlers/createBusLine.handler
    events:
      - http:
          method: POST
          path: /busline
  getBusLines:
    handler: src/handlers/getBusLines.handler
    events:
      - http:
          method: GET
          path: /buslines
  getBusLine:
    handler: src/handlers/getBusLine.handler
    events:
      - http:
          method: GET
          path: /busline/{id}        
  createBusType:
    handler: src/handlers/createBusType.handler
    events:
      - http:
          method: POST
          path: /bustype

custom:
  BusLinesTable:
    name: !Ref BusLinesTable
    arn: !GetAtt BusLinesTable.Arn
  BusTypesTable:
    name: !Ref BusTypesTable
    arn: !GetAtt BusTypesTable.Arn